# Generated by Django 3.1.4 on 2021-01-07 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import listas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default='09468e541a1e4129a5c297db427d9f90', editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nb', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to=listas.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.CharField(default=listas.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nb', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.CharField(default=listas.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nb', models.CharField(default='Lista BSH4y', max_length=30)),
                ('slugUrl', models.SlugField(default='knZdr', editable=False, max_length=20, unique=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.tipo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
