# Generated by Django 3.1.4 on 2021-01-07 20:08

from django.db import migrations, models
import django.db.models.deletion
import listas.models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listas.lista'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='e0e24970023c4039ad88ae12e379f343', editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista x80GQ', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='kwHDh', editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.CharField(default=listas.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nb', models.CharField(max_length=30)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listas.tipo')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listas.state'),
        ),
    ]
