# Generated by Django 3.1.4 on 2021-01-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0004_auto_20210108_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['nb']},
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='834dbbf0e1dc42568824921466bb6678', editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista 5P2HQ', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='wgwj9', editable=False, max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='state',
            name='tipo',
        ),
        migrations.AddField(
            model_name='state',
            name='tipo',
            field=models.ManyToManyField(to='listas.Tipo'),
        ),
    ]
