# Generated by Django 3.1.4 on 2021-01-08 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listas', '0005_auto_20210108_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default='279d4ef6d28b47dc9171a3d11ab94fe3', editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista SvSB3', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='vtyFD', editable=False, max_length=20, unique=True),
        ),
    ]
