# Generated by Django 3.1.5 on 2021-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0008_auto_20210108_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista xDrcV', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='XX44nX5CWqpFG7t5R9lN', editable=False, max_length=20, unique=True),
        ),
    ]
