# Generated by Django 3.1.5 on 2021-01-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0011_auto_20210127_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista gTM0n', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='DXZByNtJ6mPgnp4ZDtbS', editable=False, max_length=20, unique=True),
        ),
    ]
