# Generated by Django 3.1.5 on 2021-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0012_auto_20210127_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista cR4bp', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='Lym0g2ptWQs50dFQQPqq', editable=False, max_length=20, unique=True),
        ),
    ]
