# Generated by Django 3.1.5 on 2021-01-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0015_auto_20210129_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='icon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista ppnwh', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='BQPx84m3MVx', editable=False, max_length=20, unique=True),
        ),
    ]
