# Generated by Django 3.1.5 on 2021-02-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0017_auto_20210217_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista pHVJd', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='kM5yfWGTK0w', editable=False, max_length=20, unique=True),
        ),
    ]
