# Generated by Django 3.1.5 on 2021-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0020_auto_20210218_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nb',
            field=models.CharField(default='Lista DzbTC', max_length=30),
        ),
        migrations.AlterField(
            model_name='lista',
            name='slugUrl',
            field=models.SlugField(default='6RzTDjxYtQF', editable=False, max_length=20, unique=True),
        ),
    ]
