# Generated by Django 3.1.5 on 2021-06-01 02:48

import cart.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0010_auto_20210601_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.CharField(default=cart.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=cart.models.get_RandomString, max_length=5, unique=True)),
                ('products', models.ManyToManyField(to='tienda.Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.CharField(default=cart.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=cart.models.get_RandomString, max_length=10, unique=True)),
                ('products', models.ManyToManyField(to='tienda.Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
