# Generated by Django 3.1.5 on 2021-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20210601_0247'),
        ('cart', '0002_auto_20210602_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.IntegerField(choices=[('0', 'Iniciado'), ('1', 'Acabado')], default='0'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, through='cart.Compras', to='tienda.Producto'),
        ),
    ]
