# Generated by Django 3.1.5 on 2021-06-02 18:45

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210602_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.CharField(default=cart.models.generate_uuid, editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
