# Generated by Django 3.1.5 on 2021-06-02 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20210601_0247'),
        ('cart', '0004_auto_20210602_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='cart',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='product',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
    ]
