# Generated by Django 3.1.5 on 2021-04-23 18:23

from django.db import migrations, models
import django.db.models.deletion
import tienda.model_ext.case
import tienda.model_ext.caseFan
import tienda.model_ext.cpu
import tienda.model_ext.generales
import tienda.model_ext.gpu
import tienda.model_ext.motherboard
import tienda.model_ext.ram
import tienda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, default=tienda.models.get_RandomString, max_length=20, unique=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Motherboard', 'Motherboard'), ('GPU', 'Gpu')], default='GPU', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.caseFan.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.caseFan.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.caseFan.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.caseFan.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.gpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.gpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoreFamily',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.cpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.cpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ECCRAM',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.ram.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.ram.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ethernet',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.motherboard.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.motherboard.get_RandomString, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalPower',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.gpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.gpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameSync',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.gpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.gpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontPanelUSB',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.case.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.case.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrateGraphic',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.cpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.cpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.gpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.gpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LED',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.caseFan.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.caseFan.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.models.get_RandomString, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, default=tienda.models.get_RandomString, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryType',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.motherboard.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.motherboard.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroArch',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.cpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.cpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.case.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('capacidad', models.IntegerField(default=333, verbose_name='Capacidad watt')),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.case.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.cpu.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.cpu.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SidePanelWindow',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.case.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.case.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.caseFan.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('size', models.IntegerField(default=333, verbose_name='Tamaño mm')),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.caseFan.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLI',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TiemposRAM',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.ram.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.ram.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCase',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.case.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.case.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMemory',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wireless',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.motherboard.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.motherboard.get_RandomString, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(default=tienda.models.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.models.get_RandomString, max_length=10, unique=True)),
                ('precio', models.FloatField()),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.FloatField(default=0, help_text='Descuento en 0, no tiene')),
                ('photo', models.ImageField(upload_to=tienda.models.get_upload_path)),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.category')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.manufacturer', verbose_name='Compañía')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.CharField(default=tienda.model_ext.generales.generate_uuid, editable=False, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=20, unique=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.typeproduct', verbose_name='Compañía')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('speed', models.IntegerField(default=0, verbose_name='Velocidad en Mhz')),
                ('latency', models.FloatField(default=5.625, verbose_name='Latencia en ns')),
                ('voltage', models.FloatField(default=1.2, verbose_name='Voltaje en v')),
                ('heatSpreader', models.BooleanField(default=False, verbose_name='Dicipador')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color', verbose_name='Color')),
                ('ecc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.eccram', verbose_name='Color')),
                ('form_Factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.formfactor', verbose_name='Dimensiones')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tiemposram', verbose_name='Tiempos')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.typememory', verbose_name='Tipo')),
            ],
            bases=('tienda.producto',),
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('maxMemory', models.IntegerField(default=2, verbose_name='Memoria RAM máxima')),
                ('memorySlot', models.IntegerField(default=2, verbose_name='Conectores de RAM')),
                ('pciX16Slot', models.IntegerField(default=2, verbose_name='Conectores PCI x16')),
                ('pciX8Slot', models.IntegerField(default=2, verbose_name='Conectores PCI x8')),
                ('pciX4Slot', models.IntegerField(default=2, verbose_name='Conectores PCI x4')),
                ('pciX1Slot', models.IntegerField(default=2, verbose_name='Conectores PCI x1')),
                ('pciSlot', models.IntegerField(default=2, verbose_name='Conectores PCI')),
                ('sata3Port', models.IntegerField(default=2, verbose_name='Puertos SATA 3GB/s')),
                ('sata6Port', models.IntegerField(default=2, verbose_name='Puertos SATA 6GB/s')),
                ('m2Slot', models.IntegerField(default=2, verbose_name='Conectores M2')),
                ('mSataSlot', models.IntegerField(default=2, verbose_name='Conectores M2Sata')),
                ('boarVideo', models.BooleanField(default=False, verbose_name='Video en Board')),
                ('suportECC', models.BooleanField(default=False, verbose_name='Soporte para ECC')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.chipset', verbose_name='Chipset')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color', verbose_name='Color')),
                ('ethernet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ethernet', verbose_name='Red')),
                ('form_Factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.formfactor', verbose_name='Tamaño')),
                ('memoryType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.memorytype', verbose_name='Tipo de RAM')),
                ('sli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.sli', verbose_name='CrossFire / SLI')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.socket', verbose_name='Socket')),
                ('wireless', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.wireless', verbose_name='Conexión Inalámbrica')),
            ],
            bases=('tienda.producto',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('core_clock', models.IntegerField(default=0, verbose_name='Velocidad en Mhz')),
                ('boost_clock', models.IntegerField(default=0, verbose_name='Velocidad con OverClock en Mhz')),
                ('length', models.IntegerField(default=333, verbose_name='Tamaño mm')),
                ('tdp', models.IntegerField(default=10, verbose_name='Potencia Electrica')),
                ('dvi_port', models.IntegerField(default=10, verbose_name='Puertos DVI')),
                ('hdmi_port', models.IntegerField(default=10, verbose_name='Puertos HDMI')),
                ('display_port', models.IntegerField(default=10, verbose_name='Puertos DisplayPort')),
                ('mini_display_port', models.IntegerField(default=10, verbose_name='Puertos MIni-DisplayPort')),
                ('expansion_width', models.IntegerField(default=10, verbose_name='Ancho del conector de expansión')),
                ('chipset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.chipset', verbose_name='Chipset')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color', verbose_name='Color')),
                ('cooling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cooling', verbose_name='Enfrieamiento')),
                ('external_power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.externalpower', verbose_name='Fuente de alimentación')),
                ('frame_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.framesync', verbose_name='Interfaz')),
                ('inteface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.interface', verbose_name='Interfaz')),
                ('sli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.sli', verbose_name='CrossFire / SLI')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.typememory', verbose_name='Tipo')),
            ],
            bases=('tienda.producto',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('coreCount', models.IntegerField(default=1, verbose_name='Nucleos')),
                ('coreClok', models.FloatField(default=1.1, verbose_name='Frecuencia')),
                ('tdp', models.IntegerField(default=10, verbose_name='Potencia Electrica')),
                ('suportECC', models.BooleanField(default=False, verbose_name='Soporte para ECC')),
                ('coreFamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.corefamily', verbose_name='Generacion')),
                ('graphics', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.integrategraphic', verbose_name='Tarjeta Gráfica Integrada')),
                ('microArch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.microarch', verbose_name='Micro Arquitectura')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.serie', verbose_name='Serie')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.socket', verbose_name='Socket')),
            ],
            bases=('tienda.producto',),
        ),
        migrations.CreateModel(
            name='CaseFan',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de Fans')),
                ('pwm', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color', verbose_name='Color')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.connector', verbose_name='Tipo de conector')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.controller', verbose_name='Tipo de controlador')),
                ('led', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.led', verbose_name='Color de los led')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.size', verbose_name='Tamaño en mm')),
            ],
            bases=('tienda.producto',),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tienda.producto')),
                ('external_bays_5', models.IntegerField(default=0, verbose_name='Baías externas de 5.25 pulgadas')),
                ('external_bays_3', models.IntegerField(default=0, verbose_name='Baías externas de 3.5 pulgadas')),
                ('internal_bays_3', models.IntegerField(default=0, verbose_name='Baías internas de 3.5 pulgadas')),
                ('internal_bays_2', models.IntegerField(default=0, verbose_name='Baías internas de 2.5 pulgadas')),
                ('full_h_expansion_slot', models.IntegerField(default=0, verbose_name='Conectores de expansión de tamaño completo')),
                ('half_h_expansion_slot', models.IntegerField(default=0, verbose_name='Conectores de expansión de tamaño medio')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.color', verbose_name='Color')),
                ('formFactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.formfactor', verbose_name='Tamaño')),
                ('front_panel_USB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.frontpanelusb', verbose_name='Tipo de Chacis')),
                ('power_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.powersupply', verbose_name='Capacidad de la fuente')),
                ('side_panel_window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.sidepanelwindow', verbose_name='Tipo de panel lateral')),
                ('type_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.typecase', verbose_name='Tipo de Chacis')),
            ],
            bases=('tienda.producto',),
        ),
    ]
