# Generated by Django 3.1.5 on 2021-04-26 19:45

from django.db import migrations, models
import tienda.model_ext.generales


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20210423_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='category'),
        ),
        migrations.AlterField(
            model_name='chipset',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='chipset',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='formfactor',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='sli',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='sli',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='socket',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='socket',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='typememory',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='typememory',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='nombre',
            field=models.CharField(max_length=23, unique=True),
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='slug',
            field=models.SlugField(blank=True, default=tienda.model_ext.generales.get_RandomString, max_length=23, unique=True),
        ),
    ]
