# Generated by Django 3.1.5 on 2021-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_auto_20210426_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.ManyToManyField(to='tienda.TypeProduct'),
        ),
    ]
