# Generated by Django 3.1.5 on 2021-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210513_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='amount_stock',
            field=models.IntegerField(default=0),
        ),
    ]
