# Generated by Django 3.1.5 on 2021-06-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_auto_20210513_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaCompra',
        ),
        migrations.DeleteModel(
            name='ListaDeseos',
        ),
    ]
