# Generated by Django 3.1.2 on 2020-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(choices=[('A1', 'Mueble grande'), ('A2', 'Mueble mediando'), ('C1', 'Cocina estante'), ('C2', 'Cocina hueco pared'), ('R1', 'Refrigerador'), ('E1', 'Escaparate Emilito'), ('E2', 'Escaparate Padres')], max_length=2)),
                ('tipo', models.CharField(choices=[('Alimento', 'Alimento'), ('Aseo', 'Aseo'), ('Electronica', 'Electronica'), ('Hardware', 'Construccion o mantenimiento'), ('Otro', 'Otro tipo de producto')], max_length=11)),
                ('photo', models.ImageField(upload_to='almacen/media/almacen')),
            ],
        ),
    ]
