# Generated by Django 3.1.2 on 2020-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='photo',
            field=models.ImageField(upload_to='media/almacen'),
        ),
    ]
