# Generated by Django 3.1.4 on 2020-12-17 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_auto_20201217_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='file',
        ),
        migrations.AddField(
            model_name='reportes',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 12, 17)),
        ),
        migrations.AddField(
            model_name='reportes',
            name='file_path',
            field=models.FilePathField(null=True, path='media/pdf_repo'),
        ),
    ]
