# Generated by Django 3.1.4 on 2020-12-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_auto_20201217_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='fecha_creacion',
        ),
    ]
