# Generated by Django 3.1.4 on 2020-12-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_remove_reportes_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='file_path',
        ),
    ]
