# Generated by Django 3.1.4 on 2020-12-17 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_auto_20201217_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 12, 17)),
        ),
    ]
