# Generated by Django 3.1.4 on 2020-12-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_reportes_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='file_path',
            field=models.FilePathField(null=True, path='media/pdf_repo'),
        ),
    ]
