# Generated by Django 3.1.4 on 2020-12-18 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_reportes_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
