# Generated by Django 3.1.4 on 2020-12-22 18:19

import almacen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_auto_20201218_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='url_change',
            field=models.CharField(default=almacen.models.generate_uuid, editable=False, max_length=40, unique=True),
        ),
    ]
