# Generated by Django 3.1.4 on 2020-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_reportes_url_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='slug_url',
            field=models.SlugField(blank=True, default='GyyVGVqmBBD96PNbJlf7N2F9d6cd15mZvX9XfbSn', max_length=40, unique=True),
        ),
    ]
