# Generated by Django 3.1.4 on 2021-01-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen', '0015_auto_20201228_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='slug_url',
            field=models.SlugField(blank=True, default='JylW7v4GwG0XPCN5MKmj8bY4r1VnN78kqGYjVQWd', max_length=40, unique=True),
        ),
    ]
