# Generated by Django 3.1.4 on 2021-01-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_auto_20210104_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='photo',
            field=models.ImageField(upload_to='almacen'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='slug_url',
            field=models.SlugField(blank=True, default='MSX1KBRD5HQCpCMBbvHkpx6bC8H9wM46FDrKrxN2', max_length=40, unique=True),
        ),
    ]
