# Generated by Django 3.1.5 on 2021-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_auto_20210217_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudas',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
