"""
Django settings for hogar project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^yy90z(yp9_-0@j6!cf2e3yljgt1-x4aeqwu4cfy8v%c)eay$)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [

    # Installed apps
    'almacen',
    'economia',
    'user',
    'dal',
    'dal_select2',
    'celery',
    'kronos',
    'apscheduler',
    # 'django_celery_beat'
    'listas',
    'django.contrib.sites',
    'django_crontab',
    # "django_cron",
    'allauth',
    'allauth.account',
    'crispy_forms',
    'django_filters',
    'notifications',
    'django_extensions',
    'rolepermissions',
    'analytical',

    #'almacen.apps.AlmacenConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',



]

CRON_CLASSES = [
    "almacen.views.CronJobExportPDFClass",
]
# Installed apps settings
SITE_ID = 1

# Permissions
ROLEPERMISSIONS_MODULE = 'hogar.roles'
ROLEPERMISSIONS_REGISTER_ADMIN = True
ROLEPERMISSIONS_SUPERUSER_SUPERPOWERS = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Product versioning
PRODUCT_VERSION = "O.1"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'user.User'

ROOT_URLCONF = 'hogar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hogar.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # 'NAME': 'habilis',
        'NAME': 'hogar',
        'USER': 'hogar_user',
        # 'HOST': 'localhost',
        # 'PASSWORD': 'postgres',
        'PASSWORD': 'H0g@rU53r',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]
# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_DIR = BASE_DIR / 'static'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [STATIC_DIR]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# LOGIN
# LOGIN_URL= os.path.join(BASE_DIR, 'accounts')
LOGIN_REDIRECT_URL = '/accounts/login/?next=/almacen'
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory' #verify with an email
# ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
# ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True

# Email
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.escuela.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'no-reply@scintra.com'
# EMAIL_HOST_PASSWORD = 'S0p0rt32018$'
# DEFAULT_FROM_EMAIL = 'no-reply@scintra.com'


FILE_PATH_FIELD_DIRECTORY = BASE_DIR / 'media/pdf_repo/'
#CRONTAB_DJANGO_MANAGE_PATH = os.path.join(BASE_DIR, 'manage.py')
#CRONTAB_DJANGO_PROJECT_NAME = 'hogar'
#CRONTAB_DJANGO_SUFFIX = '2>&1'
#CRONTAB_DJANGO_PREFIX = 'pipenv run'
#CRONJOBS = [
#    ('* * * * *', 'almacen.cron.cron_job', '>> ~/file.log'),
#]

#from celery.schedules import crontab

#CELERY_TIMEZONE = "Cuba/Havana"
#CELERY_TASK_TRACK_STARTED = True
#CELERY_TASK_TIME_LIMIT = 30 * 60

#CELERY_BEAT_SCHEDULE = {
 #   'pdf_gen': {
  #      'task': 'almacen.view.pdf_gen',
   #     'schedule': crontab(minute=1),
    #}, }

ENV_PATH = os.path.join(BASE_DIR, '.env')

KRONOS_PREFIX = 'pipenv shell'

    #.format(os.path.join(BASE_DIR, '.env_constants'))
#KRONOS_POSTFIX = '>> /var/log/cron.log 2>&1'

CRONTAB_DJANGO_MANAGE_PATH = '/home/emilio/proyectos/env1/hogar/manage.py'

    #'~/proyectos/env1/hogar/manage.py'

CRONTAB_DJANGO_PREFIX = 'pipenv shell'

CRONJOBS = [
    ('* * * * *', 'almacen.cron.pdf_gen', '>> ~/proyectos/env1/hogar/file.txt'),
]