# Generated by Django 3.1.2 on 2020-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='profile/avatar.png', null=True, upload_to='profile/'),
        ),
    ]
